set character set utf8mb4;
INSERT INTO t_color (name, value) VALUES ('GREEN SEA', '#16a085');
INSERT INTO t_color (name, value) VALUES ('NEPHRITIS', '#27ae60');
INSERT INTO t_color (name, value) VALUES ('BELIZE HOLE', '#2980b9');
INSERT INTO t_color (name, value) VALUES ('MIDNIGHT', '#2c3e50');
INSERT INTO t_color (name, value) VALUES ('ASBESTOS', '#7f8c8d');
INSERT INTO t_color (name, value) VALUES ('WISTERIA', '#8e44ad');
INSERT INTO t_color (name, value) VALUES ('SILVER', '#bdc3c7');
INSERT INTO t_color (name, value) VALUES ('POMEGRANATE', '#c0392b');
INSERT INTO t_color (name, value) VALUES ('PUMPKIN', '#d35400');
INSERT INTO t_color (name, value) VALUES ('Dark Salmon', '#efa48b');
INSERT INTO t_color (name, value) VALUES ('ORANGE', '#f39c12');

INSERT INTO t_classroom (name) VALUES ('教室101');

INSERT INTO t_course (name, duration, background_color) VALUES ('语文', 60, '#f39c12');

INSERT INTO t_teacher (name, username, password) VALUES ('张老师', 'teacher1', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EH');

-- 年级: 大一/大二/大三/大四, 专业: 计算机与科学技术/软件工程/信息工程/物联网工程/网络安全, 班号: 一班/二班/三班
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一计算机与科学技术一班', '大一', '计算机与科学技术', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一计算机与科学技术二班', '大一', '计算机与科学技术', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一计算机与科学技术三班', '大一', '计算机与科学技术', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一软件工程一班', '大一', '软件工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一软件工程二班', '大一', '软件工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一软件工程三班', '大一', '软件工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一信息工程一班', '大一', '信息工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一信息工程二班', '大一', '信息工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一信息工程三班', '大一', '信息工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一物联网工程一班', '大一', '物联网工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一物联网工程二班', '大一', '物联网工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一物联网工程三班', '大一', '物联网工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一网络安全一班', '大一', '网络安全', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一网络安全二班', '大一', '网络安全', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大一网络安全三班', '大一', '网络安全', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二计算机与科学技术一班', '大二', '计算机与科学技术', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二计算机与科学技术二班', '大二', '计算机与科学技术', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二计算机与科学技术三班', '大二', '计算机与科学技术', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二软件工程一班', '大二', '软件工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二软件工程二班', '大二', '软件工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二软件工程三班', '大二', '软件工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二信息工程一班', '大二', '信息工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二信息工程二班', '大二', '信息工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二信息工程三班', '大二', '信息工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二物联网工程一班', '大二', '物联网工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二物联网工程二班', '大二', '物联网工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二物联网工程三班', '大二', '物联网工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二网络安全一班', '大二', '网络安全', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二网络安全二班', '大二', '网络安全', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大二网络安全三班', '大二', '网络安全', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三计算机与科学技术一班', '大三', '计算机与科学技术', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三计算机与科学技术二班', '大三', '计算机与科学技术', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三计算机与科学技术三班', '大三', '计算机与科学技术', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三软件工程一班', '大三', '软件工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三软件工程二班', '大三', '软件工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三软件工程三班', '大三', '软件工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三信息工程一班', '大三', '信息工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三信息工程二班', '大三', '信息工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三信息工程三班', '大三', '信息工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三物联网工程一班', '大三', '物联网工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三物联网工程二班', '大三', '物联网工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三物联网工程三班', '大三', '物联网工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三网络安全一班', '大三', '网络安全', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三网络安全二班', '大三', '网络安全', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大三网络安全三班', '大三', '网络安全', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四计算机与科学技术一班', '大四', '计算机与科学技术', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四计算机与科学技术二班', '大四', '计算机与科学技术', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四计算机与科学技术三班', '大四', '计算机与科学技术', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四软件工程一班', '大四', '软件工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四软件工程二班', '大四', '软件工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四软件工程三班', '大四', '软件工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四信息工程一班', '大四', '信息工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四信息工程二班', '大四', '信息工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四信息工程三班', '大四', '信息工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四物联网工程一班', '大四', '物联网工程', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四物联网工程二班', '大四', '物联网工程', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四物联网工程三班', '大四', '物联网工程', '三班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四网络安全一班', '大四', '网络安全', '一班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四网络安全二班', '大四', '网络安全', '二班');
INSERT INTO t_class (name, grade, major, class_number) VALUES ('大四网络安全三班', '大四', '网络安全', '三班');

INSERT INTO t_student (name, class_id, username, password) VALUES ('小明', 1, 'student1', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EH');
INSERT INTO t_student (name, class_id, username, password) VALUES ('小红', 1, 'student2', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EH');
INSERT INTO t_student (name, class_id, username, password) VALUES ('小刚', 2, 'student3', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EH');
